"""added user_role to Users

Revision ID: 68ae06237ac6
Revises: bd3a7c896278
Create Date: 2020-05-14 22:35:15.908835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ae06237ac6'
down_revision = 'bd3a7c896278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('auth_token_expiration', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_auth_token'), 'users', ['auth_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_token'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'auth_token_expiration')
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###
