"""Implemented user auth tokens

Revision ID: bd3a7c896278
Revises: 6dbacd544b85
Create Date: 2020-05-14 12:23:27.562782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3a7c896278'
down_revision = '6dbacd544b85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_token', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('auth_token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_auth_token'), 'users', ['auth_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_token'), table_name='users')
    op.drop_column('users', 'auth_token_expiration')
    op.drop_column('users', 'auth_token')
    # ### end Alembic commands ###
