"""add email_verified_date to user model

Revision ID: 1aadc243077b
Revises: 3c6d61faaab9
Create Date: 2020-09-07 21:22:11.462635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aadc243077b'
down_revision = '3c6d61faaab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    # ### end Alembic commands ###
