"""Make Account description and Transaction note non-nullable.

Revision ID: 39479715d3cd
Revises: 1b1cd0d1741f
Create Date: 2020-05-26 19:24:54.461691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39479715d3cd'
down_revision = '1b1cd0d1741f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transactions', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('accounts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
