"""Add date column to transactions

Revision ID: 567bedd82000
Revises: 39479715d3cd
Create Date: 2020-05-27 00:23:49.708861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567bedd82000'
down_revision = '39479715d3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
