"""make transaction date non nullable

Revision ID: 59d6bec11f6c
Revises: 567bedd82000
Create Date: 2020-05-27 00:25:48.348387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d6bec11f6c'
down_revision = '567bedd82000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
