"""Removed AccountTransactions table making Transactions a child of Account

Revision ID: 6dbacd544b85
Revises: 18e92279075f
Create Date: 2020-05-04 19:35:18.358633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbacd544b85'
down_revision = '18e92279075f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_transactions')
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'account_id')
    op.create_table('account_transactions',
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='account_transactions_account_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name='account_transactions_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('account_id', 'transaction_id', name='account_transactions_pkey')
    )
    # ### end Alembic commands ###
